const api=require('../../utils/api'),content=require('../../data/content'),play=require('../../data/play');
const fresh=()=>({date:[new Date().getFullYear(),String(new Date().getMonth()+1).padStart(2,'0'),String(new Date().getDate()).padStart(2,'0')].join('-'),title:'',body:'',mood:'开心'});
Page({data:{tabs:['首页','相册','日记','互动','旅行','视频'],tab:'首页',role:null,categories:['全部','小小日常','书店约会','雨天散步','海洋馆','一起冒险'],category:'全部',photos:content.photos,images:{},entries:[],draft:fresh(),moods:['心动','开心','想念','平静','有点低落'],mode:'quiz',room:null,note:'',busy:false,error:'',clips:[{id:1,src:''},{id:2,src:''}],markers:[{id:1,latitude:29.7088,longitude:120.244,title:'诸暨',callout:{content:'♡ 诸暨',display:'ALWAYS'}},{id:2,latitude:30.0003,longitude:120.5821,title:'绍兴',callout:{content:'♡ 绍兴',display:'ALWAYS'}}]},
onShow(){if(!getApp().globalData.role){wx.reLaunch({url:'/pages/login/index'});return;}this.setData({role:getApp().globalData.role});this.refresh();this.timer=setInterval(()=>this.refresh(),3000);},onHide(){clearInterval(this.timer);},onUnload(){clearInterval(this.timer);},
switchTab(e){this.setData({tab:e.currentTarget.dataset.tab,error:''});this.refresh();},filter(e){const category=e.currentTarget.dataset.category;this.setData({category,photos:content.photos.filter(p=>category==='全部'||p.category===category)});},
async refresh(){if(this.syncing)return;this.syncing=true;const tab=this.data.tab,mode=this.data.mode;try{if(tab==='日记'){const d=await api.request('/api/diary');this.setData({entries:d.entries});}if(tab==='互动'){const r=await api.request('/api/together?mode='+mode);if(mode===this.data.mode){const q=play.questions[r.round%play.questions.length];this.setData({room:r,question:q,submitted:r.submitted[r.role],plan:r.plan===null?'':play.dates[r.plan],answerHim:r.answers?(mode==='quiz'?q.a[Number(r.answers.him)]:r.answers.him):'',answerHer:r.answers?(mode==='quiz'?q.a[Number(r.answers.her)]:r.answers.her):''});}}this.setData({error:''});}catch(e){this.setData({error:e.message});}finally{this.syncing=false;}},
async loadPhoto(e){const id=e.currentTarget.dataset.id;try{const src=await api.media('/photos/photo-'+id+'.jpg');this.setData({['images.'+id]:src});}catch(e){this.setData({error:e.message});}},preview(e){const src=this.data.images[e.currentTarget.dataset.id];wx.previewImage({urls:[src],current:src});},
draftInput(e){this.setData({['draft.'+e.currentTarget.dataset.field]:e.detail.value});},dateChange(e){this.setData({'draft.date':e.detail.value});},moodChange(e){this.setData({'draft.mood':this.data.moods[e.detail.value]});},newDiary(){this.setData({draft:fresh()});},editDiary(e){this.setData({draft:{...this.data.entries.find(d=>d.id===e.currentTarget.dataset.id)}});},
async saveDiary(){if(this.data.busy)return;this.setData({busy:true,error:''});try{const draft=this.data.draft;await api.request('/api/diary','PUT',{...draft,id:draft.id||'mini-'+Date.now()+'-'+Math.random().toString(36).slice(2)});this.newDiary();await this.refresh();}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
modeChange(e){if(this.data.busy)return;this.setData({mode:e.currentTarget.dataset.mode,room:null});this.refresh();},noteInput(e){this.setData({note:e.detail.value});},
async action(e){if(this.data.busy||!this.data.room)return;this.setData({busy:true,error:''});try{await api.request('/api/together','POST',{mode:this.data.mode,round:this.data.room.round,action:e.currentTarget.dataset.action,answer:this.data.mode==='notes'?this.data.note:String(e.currentTarget.dataset.answer)});this.setData({note:''});await this.refresh();}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
async loadVideo(e){const id=Number(e.currentTarget.dataset.id);try{const src=await api.media('/videos/clip-'+id+'.mp4');this.setData({['clips['+(id-1)+'].src']:src});}catch(e){this.setData({error:e.message});}},videoPlay(e){this.data.clips.filter(c=>c.id!==Number(e.currentTarget.dataset.id)).forEach(c=>wx.createVideoContext('clip'+c.id).pause());},
async logout(){try{await api.request('/api/auth/logout','POST');}catch(e){}api.clear();wx.reLaunch({url:'/pages/login/index'});}
});