import {CouplePlay} from './CouplePlay';
import {Diary} from './Diary';
import {lazy,Suspense} from 'react';
const TravelMap=lazy(()=>import('./TravelMap').then(m=>({default:m.TravelMap}))); 
import {photos,site} from './content';
import {LoveParticles,sendLove} from './LoveParticles';
import { useState, useEffect, useRef } from 'react';
import { Flame, Heart, ArrowDown, ArrowUpRight, ArrowLeft, ArrowRight, X, EnvelopeSimple, Sparkle, Camera, Check } from '@phosphor-icons/react';
export function App(){
 const [motion,setMotion]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 const [filter,setFilter]=useState('全部回忆'); const [selected,setSelected]=useState(null); const [letter,setLetter]=useState(false); const [saved,setSaved]=useState(false); const lastFocus=useRef(null); const closeRef=useRef(null);
 const filtered=photos.filter(p=>filter==='全部回忆'||p.category===filter);
 const chapters=['小小日常','书店约会','雨天散步','海洋馆','一起冒险'];
 const chapterNotes={'小小日常':'把平凡的小事，留成我们的纪念。','书店约会':'书页翻过，喜欢留下。','雨天散步':'听雨，也听彼此。','海洋馆':'一起看过的蓝，慢慢收藏。','一起冒险':'另一个世界，也有我们的合照。'};
 const opened=selected!==null||letter;
 function openPhoto(p){lastFocus.current=document.activeElement;setSelected(photos.findIndex(x=>x.id===p.id));}
 function close(){setSelected(null);setLetter(false);setTimeout(()=>lastFocus.current?.focus(),0);}
 useEffect(()=>{if(!opened)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();function keys(e){if(e.key==='Escape')close();if(selected!==null&&e.key==='ArrowRight')setSelected(n=>(n+1)%photos.length);if(selected!==null&&e.key==='ArrowLeft')setSelected(n=>(n+photos.length-1)%photos.length);if(e.key==='Tab'){const nodes=[...document.querySelectorAll('.modal button,.modal a')];const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}window.addEventListener('keydown',keys);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',keys);};},[opened,selected]);
 return <><div className="romance-backdrop" aria-hidden="true"><span className="garden garden-left">✿</span><span className="garden garden-right">✿</span><span className="paper-heart">♡</span></div><LoveParticles enabled={motion}/><header className="site-header"><a href="#home" className="brand"><Flame weight="fill"/><span>{site.name}<span className="brand-sub">OUR EVERYDAY JOURNAL</span></span></a><nav aria-label="主导航"><a href="#memories">回忆手账</a><a href="#diary">恋爱日记</a><a href="#together">情侣互动</a><a href="#travel">旅行足迹</a><a href="#videos">动态回忆</a><a href="#letter">写给你的信</a></nav><span className="header-note">我们的故事，持续更新 <Heart weight="fill"/></span></header>
 <main><section id="home" className="hero"><div className="hero-copy"><div className="eyebrow"><span/> {site.currentTheme.label}</div><h1>和你，续写到<br/>第 <button className="day-number love-trigger" onClick={sendLove} aria-label="点击1000天，绽放心动粒子">{site.currentTheme.days}</button> 天<span className="title-dot">。</span></h1><p className="hero-description">从一句分享开始，把日常聊成了喜欢。<br/>不知不觉，我们的火花已经亮了 1000 天。</p><a className="primary-button" href="#memories">翻开我们的回忆 <ArrowDown size={17}/></a><div className="motion-controls"><button aria-pressed={motion} onClick={()=>setMotion(!motion)}><Sparkle size={14}/> 心动粒子 · {motion?'开':'关'}</button><span>轻触 1000，让心动绽放</span></div><div className="hero-footnote"><span className="mini-avatars"><img src="/photos/avatar-him.jpg" alt="男生插画头像"/><img src="/photos/avatar-her.jpg" alt="女生插画头像"/></span><span>{site.tagline}</span></div></div>
 <div className="hero-collage"><div className="small-note">the best part of my every day</div><div className="polaroid back-photo"><img src="/photos/photo-4.jpg" alt="抬头望向天空的雨天回忆"/><span>有你，雨天也可爱。</span></div><button className="polaroid main-photo" onClick={()=>openPhoto(photos[0])} aria-label="放大牵手照"><img src="/photos/photo-7.jpg" alt="戴着戒指的两只手牵在一起"/><span>想和你，一直这样牵着手。<Heart size={17}/></span></button><div className="spark-stamp"><Flame size={25} weight="fill"/><strong>{site.currentTheme.days}</strong><span>DAYS OF US</span></div><span className="collage-caption">{site.currentTheme.caption} <Heart weight="fill" size={14}/></span></div></section>
 <div className="cartoon-bookmark" aria-label="情侣卡通留言"><img src="/photos/avatar-her.jpg" alt="女生卡通头像"/><p>今天的可爱，也一起收藏。</p><img src="/photos/avatar-him.jpg" alt="男生卡通头像"/></div><div className="chapter-divider"><span>一点一滴，都是我们</span><Heart weight="fill" size={15}/><span>EVERY LITTLE MOMENT COUNTS</span></div>
 <section id="memories" className="memories"><div className="section-heading"><div><div className="eyebrow">OUR MEMORIES / 回忆手账</div><h2>把喜欢，装订成册<span>。</span></h2><p>那些普通的瞬间，因为有你，都变得值得收藏。</p></div><span className="section-aside"><Camera size={20}/> {photos.length} 张回忆 · 无数次心动</span></div><div className="filters" role="group" aria-label="回忆分类">{['全部回忆','小小日常','雨天散步','书店约会','海洋馆','一起冒险'].map(t=><button key={t} aria-pressed={filter===t} className={filter===t?'active':''} onClick={()=>setFilter(t)}>{t}{t==='全部回忆'&&<span>{String(photos.length).padStart(2,'0')}</span>}</button>)}</div><div className="album-chapters">{chapters.filter(t=>filter==='全部回忆'||filter===t).map((category,chapter)=><div className="album-chapter" key={category}><div className="album-chapter-heading"><span className="chapter-number">{String(chapters.indexOf(category)+1).padStart(2,'0')}</span><div><h3>{category}</h3><p>{chapterNotes[category]}</p></div><span className="chapter-count">{photos.filter(p=>p.category===category).length} 帧收藏</span></div><div className="photo-grid">{filtered.filter(p=>p.category===category).map((p,i)=><button className={'memory-photo memory-'+p.id+(p.shape==='game'?' game-photo':'')} key={p.id} onClick={()=>openPhoto(p)}><div className="photo-wrap"><img loading="lazy" src={'/photos/photo-'+p.id+'.jpg'} alt={p.title}/><span className="photo-expand"><ArrowUpRight size={22}/></span></div><div className="photo-meta"><span className="photo-index">♡</span><h3>{p.title}</h3><Heart size={17}/></div><p>{p.note}</p></button>)}</div></div>)}</div><div className="album-end"><Sparkle size={18}/><span>相册会慢慢变厚，我们的故事也是。</span><Sparkle size={18}/></div></section>
 <CouplePlay/><Diary/><Suspense fallback={<p className="local-note">正在准备旅行地图……</p>}><TravelMap/></Suspense><section className="video-memories" id="videos"><div className="eyebrow">MOVING MEMORIES</div><h2>让回忆，再播放一次。</h2><div className="video-grid">{[1,2].map(i=><figure key={i}><video controls playsInline preload="none" poster={'/videos/poster-'+i+'.jpg'} onPlay={e=>document.querySelectorAll('video').forEach(v=>{if(v!==e.currentTarget)v.pause();})}><source src={'/videos/clip-'+i+'.mp4'} type="video/mp4"/>你的浏览器暂不支持视频播放。</video><figcaption>回忆片段 {String(i).padStart(2,'0')}</figcaption></figure>)}</div></section>
 <section className="letter-section" id="letter"><div className="letter-intro"><div className="eyebrow">LETTERS TO YOU / 写给你</div><h2>还有一些话，<br/>想认真写给你。</h2><p>关于这 1000 天，也关于以后。</p></div><button className="letter-card" onClick={(e)=>{sendLove(e);lastFocus.current=document.activeElement;setLetter(true);}}><span className="letter-top">TO: 最特别的你 <span>No. 1000</span></span><EnvelopeSimple size={46} weight="thin"/><span className="letter-title">一封写给你的信</span><span className="letter-cartoon-pair" aria-hidden="true"><img src="/photos/avatar-him.jpg" alt=""/><img src="/photos/avatar-her.jpg" alt=""/></span><span className="letter-open">轻轻拆开 <ArrowUpRight size={17}/></span></button></section>
 <footer><Flame weight="fill" size={22}/><p>日子慢慢过，故事慢慢写。</p><span>OUR EVERYDAY JOURNAL · 你和我，未完待续</span><a href="#home">回到开始 <ArrowUpRight size={14}/></a></footer></main>
 {opened&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)close();}}><div className={'modal '+(letter?'letter-modal':'photo-modal')} role="dialog" aria-modal="true" aria-label={letter?'写给你的信':'回忆照片'}><button ref={closeRef} className="close-button" onClick={close} aria-label="关闭"><X size={22}/></button>{letter?<><span className="eyebrow">A LETTER FOR YOU · 1000 DAYS</span><h2>亲爱的你：</h2><div className="letter-body"><p>原来，1000 天可以藏在那么多小事里。</p><p>是一条想分享给你的视频，是看到有趣的事就想找你，是忙碌一天之后，还想和你说说话。</p><p>翻着这些照片才发现，我喜欢的从来不只是某一个特别的日子。是下雨时一起撑的伞，是书店里停下来的片刻，也是那些没有安排、却因为有你而变得可爱的日常。</p><p>谢谢你，让屏幕里的小火花，有了生活里的温度。</p><p>第 1000 天快乐。以后的日子，也想继续和你分享。</p></div><div className="letter-sign">写在我们的第 1000 天 <Heart weight="fill"/></div><button className="primary-button letter-keep" onClick={(e)=>{sendLove(e);setSaved(true);}}>{saved?<><Check/> 已把这份心意收好</>:<>收好这封信 <Heart/></>}</button></>:<><img className="full-photo" src={'/photos/photo-'+photos[selected].id+'.jpg'} alt={photos[selected].title}/><div className="lightbox-bottom"><button aria-label="上一张" onClick={()=>setSelected((selected+photos.length-1)%photos.length)}><ArrowLeft size={22}/></button><div><h3>{photos[selected].title}</h3><p>{selected+1} / {photos.length} · {photos[selected].note}</p></div><button aria-label="下一张" onClick={()=>setSelected((selected+1)%photos.length)}><ArrowRight size={22}/></button></div></>}</div></div>}
 </>;
}

