import {useState,useRef,useEffect} from 'react';
import {PencilSimple,DownloadSimple,Heart,BookOpen,Check} from '@phosphor-icons/react';
const KEY='our-everyday.diary.v1';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export function Diary(){
 const [legacy,setLegacy]=useState(()=>{try{const a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a.filter(e=>typeof e.id==='string'&&typeof e.title==='string'&&typeof e.body==='string'):[];}catch{return [];}});
 const [entries,setEntries]=useState([]);const [role,setRole]=useState(null);const [syncing,setSyncing]=useState(false);const [saving,setSaving]=useState(false);
 const [draft,setDraft]=useState(null);const [message,setMessage]=useState('');const titleRef=useRef(null);
 async function refresh(){setSyncing(true);try{const r=await fetch('/api/diary');const d=await r.json();if(!r.ok)throw Error(d.error);setEntries(d.entries);setRole(d.role);}catch(e){setMessage(e.message||'同步失败，请重试。');}finally{setSyncing(false);}}
 useEffect(()=>{refresh();const id=setInterval(()=>{if(!document.hidden)refresh();},15000);const focus=()=>refresh();window.addEventListener('focus',focus);return()=>{clearInterval(id);window.removeEventListener('focus',focus);};},[]);
 function edit(e){setDraft(e?{...e}:{id:crypto.randomUUID(),date:today(),title:'',body:'',mood:'心动'});setMessage('');setTimeout(()=>titleRef.current?.focus(),0);}
 async function save(e){e.preventDefault();if(!draft.title.trim()||!draft.body.trim()){setMessage('写下标题和正文，再收进日记吧。');return;}setSaving(true);try{const r=await fetch('/api/diary',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const d=await r.json();if(!r.ok)throw Error(d.error);setDraft(null);setMessage('已保存到网站，两个人都能看到。');await refresh();}catch(e){setMessage(e.message||'保存失败，文字已保留，请重试。');}finally{setSaving(false);}}
 async function importLegacy(){setSaving(true);try{for(const e of legacy){const r=await fetch('/api/diary',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:e.id,title:e.title,body:e.body,date:e.date,mood:e.mood||'心动'})});if(!r.ok){const d=await r.json();throw Error(d.error);}}setLegacy([]);setMessage('本机旧日记已导入，原始本地备份仍保留。');await refresh();}catch(e){setMessage('导入未全部完成：'+e.message+'。原始本地备份仍保留。');await refresh();}finally{setSaving(false);}}
 function exportEntries(){const blob=new Blob([JSON.stringify({version:1,entries},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`我们的日常-日记-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="journal-section" id="diary"><div className="section-heading"><div><div className="eyebrow">DEAR DIARY / 恋爱日记</div><h2>把今天，写给以后的我们。</h2><p>小事也值得记下。今天的心情，明天再读一遍。</p></div><div className="journal-actions"><button className="quiet-action" onClick={refresh} disabled={syncing}>{syncing?'同步中……':'刷新日记'}</button><button onClick={exportEntries} disabled={!entries.length} className="quiet-action"><DownloadSimple/> 导出备份</button><button className="primary-button" onClick={()=>edit()}><PencilSimple/> 写一篇日记</button></div></div>
 {legacy.length>0&&<div className="local-note">发现 {legacy.length} 篇本机旧日记。<button className="quiet-action" disabled={saving} onClick={importLegacy}>以当前身份导入网站</button></div>}
 <div className="cartoon-companions"><img src="/photos/avatar-her.jpg" alt="女生卡通头像"/><div><span>今天也想听你说</span><p>有趣的事、想念的话，都可以留在这里。</p></div><img src="/photos/avatar-him.jpg" alt="男生卡通头像"/></div>
 {draft&&<form className="diary-editor" onSubmit={save}><div className="editor-row"><label>记录日期<input type="date" required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>今日心情<select value={draft.mood} onChange={e=>setDraft({...draft,mood:e.target.value})}>{['心动','开心','想念','平静','有点低落'].map(m=><option key={m}>{m}</option>)}</select></label></div><label>日记标题<input ref={titleRef} required maxLength={80} placeholder="给今天起一个名字" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>想记住的话<textarea required rows={7} maxLength={20000} placeholder="今天，想和你说……" value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><div className="journal-actions"><button type="button" className="quiet-action" onClick={()=>setDraft(null)}>取消</button><button className="primary-button" type="submit" disabled={saving}><Check/> {saving?'保存中……':'保存日记'}</button></div></form>}
 <p role="status" className="diary-status">{message}</p>
 {!entries.length&&!draft?<div className="diary-empty"><BookOpen size={36} weight="thin"/><h3>我们的第一页，等你来写。</h3><p>还没有日记，从今天的一件小事开始吧。</p></div>:<div className="diary-list">{entries.map(e=><article key={e.id}><div className="entry-meta"><time>{e.date} · {e.author==='him'?'男方':'女方'}</time><span><Heart size={12}/>{e.mood}</span></div><h3>{e.title}</h3><p>{e.body}</p>{role===e.author&&<button className="quiet-action" onClick={()=>edit(e)}><PencilSimple/> 编辑这篇</button>}</article>)}</div>}
 <p className="local-note">日记保存在网站，两人登录后共享查看；仅作者可编辑。每 15 秒自动同步，也可手动刷新。</p></section>
}
