import {useEffect,useRef,useState} from 'react';
import * as echarts from 'echarts/core';
import {MapChart,EffectScatterChart} from 'echarts/charts';
import {GeoComponent,TooltipComponent} from 'echarts/components';
import {CanvasRenderer} from 'echarts/renderers';
import {MapPin,Compass,Heart} from '@phosphor-icons/react';
echarts.use([MapChart,EffectScatterChart,GeoComponent,TooltipComponent,CanvasRenderer]);
const places=[{name:'诸暨',coordinate:[120.244326,29.713662],note:'这一站，已经走进我们的故事。'},{name:'绍兴',coordinate:[120.582112,29.997117],note:'把这里的回忆，一点一点收藏。'}];
export function TravelMap(){const host=useRef(null),chart=useRef(null);const [selected,setSelected]=useState('诸暨');const [error,setError]=useState(false);const [ready,setReady]=useState(false);
 useEffect(()=>{let cancelled=false,observer;fetch('/maps/zhejiang.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(geo=>{if(cancelled)return;echarts.registerMap('our-zhejiang',geo);const c=echarts.init(host.current);chart.current=c;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;c.setOption({animation:!reduced,tooltip:{trigger:'item',formatter:p=>p.seriesType==='effectScatter'?`${p.name} · 已点亮`:`${p.name} · ${p.name==='绍兴市'?'诸暨、绍兴已点亮':'等待未来的脚步'}`},geo:{map:'our-zhejiang',roam:false,layoutCenter:['50%','50%'],layoutSize:'95%',silent:false,label:{show:true,color:'#988e84',fontSize:11},itemStyle:{areaColor:'#e8e3d8',borderColor:'#fffcf4',borderWidth:1.6,shadowColor:'#9e9080',shadowBlur:0,shadowOffsetY:8},emphasis:{disabled:true},regions:[{name:'绍兴市',itemStyle:{areaColor:'#ead3c1'},label:{show:false}}]},series:[{type:'effectScatter',coordinateSystem:'geo',data:places.map(p=>({name:p.name,value:p.coordinate})),symbolSize:12,showEffectOn:reduced?'emphasis':'render',rippleEffect:{scale:3,brushType:'stroke',period:5},itemStyle:{color:'#b66d80',shadowBlur:14,shadowColor:'#c8889699'},label:{show:true,formatter:'{b}',position:'right',offset:[6,0],color:'#805164',fontSize:13,fontWeight:600,backgroundColor:'#fff8ef',borderRadius:5,padding:[5,7]},z:10}]});c.on('click',p=>{if(places.some(x=>x.name===p.name))setSelected(p.name);});observer=new ResizeObserver(()=>c.resize());observer.observe(host.current);setReady(true);}).catch(()=>{if(!cancelled)setError(true);});return()=>{cancelled=true;observer?.disconnect();chart.current?.dispose();chart.current=null;};},[]);
 function choose(name){setSelected(name);chart.current?.dispatchAction({type:'showTip',seriesIndex:0,dataIndex:places.findIndex(p=>p.name===name)});}
 return <section id="travel" className="travel-section"><div className="section-heading"><div><div className="eyebrow">OUR LITTLE WORLD / 旅行足迹</div><h2>一起，把世界慢慢点亮。</h2><p>先从浙江开始。已点亮诸暨、绍兴，其他地方留给以后。</p></div><span className="travel-count"><Compass size={21}/> 2 个目的地</span></div><div className="travel-layout"><div className="map-board"><div className="map-caption">浙江 · 我们的探索地图</div><div ref={host} className="travel-map" role="img" aria-label="浙江旅行地图，仅诸暨和绍兴两个目的地已点亮，其他城市尚未点亮"/>{!ready&&!error&&<p className="map-loading">正在展开地图……</p>}{error&&<p className="map-loading">地图暂未加载，请刷新重试。</p>}<div className="map-legend"><span className="visited-dot"/> 已点亮 <span className="unvisited-dot"/> 待探索</div></div><aside className="travel-aside"><div className="travel-mascots"><img src="/photos/avatar-him.jpg" alt="男生卡通旅伴"/><Heart weight="fill"/><img src="/photos/avatar-her.jpg" alt="女生卡通旅伴"/></div><p className="travel-whisper">最好的旅行，是身边有你。</p><div className="place-tabs" aria-label="选择已点亮目的地">{places.map(p=><button key={p.name} aria-pressed={selected===p.name} onClick={()=>choose(p.name)}><MapPin weight={selected===p.name?'fill':'regular'}/>{p.name}<span>已点亮</span></button>)}</div><div className="place-note"><span>OUR FOOTPRINT</span><h3>{selected}</h3><p>{places.find(p=>p.name===selected).note}</p></div><small>诸暨属于绍兴市；两个标记分别记录目的地足迹。区域底色用于定位，不代表全部游览。</small></aside></div><a className="map-source" href="https://datav.aliyun.com/portal/school/atlas/area_selector" target="_blank" rel="noreferrer">地图边界来源：阿里云 DataV · 仅作旅行纪念示意</a></section>;
}
